# A CardSet object contains information about a set of Pokemon cards
# This can be changed to work for any card set, but currently the values of the Evolutions set are hard coded in
class CardSet:
    def __init__(self):
        self.cardnumber = (1,
                           2,
                           3,
                           4,
                           5,
                           6,
                           7,
                           8,
                           9,
                           10,
                           11,
                           12,
                           13,
                           14,
                           15,
                           16,
                           17,
                           18,
                           19,
                           20,
                           21,
                           22,
                           23,
                           24,
                           25,
                           26,
                           27,
                           28,
                           29,
                           30,
                           31,
                           32,
                           33,
                           34,
                           35,
                           36,
                           37,
                           38,
                           39,
                           40,
                           41,
                           42,
                           43,
                           44,
                           45,
                           46,
                           47,
                           48,
                           49,
                           50,
                           51,
                           52,
                           53,
                           54,
                           55,
                           56,
                           57,
                           58,
                           59,
                           60,
                           61,
                           62,
                           63,
                           64,
                           65,
                           66,
                           67,
                           68,
                           69,
                           70,
                           71,
                           72,
                           73,
                           74,
                           75,
                           76,
                           77,
                           78,
                           79,
                           80,
                           81,
                           82,
                           83,
                           84,
                           85,
                           86,
                           87,
                           88,
                           89,
                           90,
                           91,
                           92,
                           93,
                           94,
                           95,
                           96,
                           97,
                           98,
                           99,
                           100,
                           101,
                           102,
                           103,
                           104,
                           105,
                           106,
                           107,
                           108,
                           109,
                           110,
                           111,
                           112,
                           113)

        self.cardnamelist = ("Venusaur EX",
                             "M Venusaur EX",
                             "Caterpie",
                             "Metapod",
                             "Weedle",
                             "Kakuna",
                             "Beedrill",
                             "Tangela",
                             "Charmander",
                             "Charmeleon",
                             "Charizard",
                             "Charizard EX",
                             "M Charizard EX",
                             "Vulpix",
                             "Ninetales",
                             "Ninetales BREAK",
                             "Growlithe",
                             "Arcanine",
                             "Ponyta",
                             "Magmar",
                             "Blastoise EX",
                             "M Blastoise EX",
                             "Poliwag",
                             "Poliwhirl",
                             "Poliwrath",
                             "Slowbro EX",
                             "M Slowbro EX",
                             "Seel",
                             "Dewgong",
                             "Staryu",
                             "Starmie",
                             "Starmie BREAK",
                             "Magikarp",
                             "Gyarados",
                             "Pikachu",
                             "Raichu",
                             "Magnemite",
                             "Magneton",
                             "Voltorb",
                             "Electrode",
                             "Electabuzz",
                             "Zapdos",
                             "Nidoran ♂",
                             "Nidorino",
                             "Nidoking",
                             "Nidoking BREAK",
                             "Gastly",
                             "Haunter",
                             "Drowzee",
                             "Koffing",
                             "Mewtwo",
                             "Mewtwo EX",
                             "Mew",
                             "Sandshrew",
                             "Diglett",
                             "Dugtrio",
                             "Machop",
                             "Machoke",
                             "Machamp",
                             "Machamp BREAK",
                             "Onix",
                             "Hitmonchan",
                             "Clefairy",
                             "Pidgeot EX",
                             "M Pidgeot EX",
                             "Rattata",
                             "Raticate",
                             "Farfetch'd",
                             "Doduo",
                             "Chansey",
                             "Porygon",
                             "Dragonite EX",
                             "Blastoise Spirit Link",
                             "Brock's Grit",
                             "Charizard Spirit Link",
                             "Devolution Spray",
                             "Energy Retrieval",
                             "Full Heal",
                             "Maintenance",
                             "Misty's Determination",
                             "Pidgeot Spirit Link",
                             "Pokedex",
                             "Potion",
                             "Professor Oak's Hint",
                             "Revive",
                             "Slowbro Spirit Link",
                             "Super Potion",
                             "Switch",
                             "Venusaur Spirit Link",
                             "Double Colorless Energy",
                             "Grass Energy",
                             "Fire Energy",
                             "Water Energy",
                             "Electric Energy",
                             "Psychic Energy",
                             "Fighting Energy",
                             "Dark Energy",
                             "Metal Energy",
                             "Fairy Energy",
                             "M Venusaur EX",
                             "M Charizard EX",
                             "M Blastoise EX",
                             "Mewtwo EX",
                             "Pidgeot EX",
                             "M Pidgeot EX",
                             "Dragonite EX",
                             "Brock's Grit",
                             "Misty's Determination",
                             "Exeggutor",
                             "Flying Pikachu",
                             "Surfing Pikachu",
                             "Imakuni?'s Doduo",
                             "Here Comes Team Rocket!")

        self.pokemonlist = ("Venusaur",
                            "Mega Venusaur",
                            "Caterpie",
                            "Metapod",
                            "Weedle",
                            "Kakuna",
                            "Beedrill",
                            "Tangela",
                            "Charmander",
                            "Charmeleon",
                            "Charizard",
                            "Charizard",
                            "Mega Charizard",
                            "Vulpix",
                            "Ninetales",
                            "Ninetales",
                            "Growlithe",
                            "Arcanine",
                            "Ponyta",
                            "Magmar",
                            "Blastoise",
                            "Mega Blastoise",
                            "Poliwag",
                            "Poliwhirl",
                            "Poliwrath",
                            "Slowbro",
                            "Mega Slowbro",
                            "Seel",
                            "Dewgong",
                            "Staryu",
                            "Starmie",
                            "Starmie",
                            "Magikarp",
                            "Gyarados",
                            "Pikachu",
                            "Raichu",
                            "Magnemite",
                            "Magneton",
                            "Voltorb",
                            "Electrode",
                            "Electabuzz",
                            "Zapdos",
                            "Nidoran ♂",
                            "Nidorino",
                            "Nidoking",
                            "Nidoking",
                            "Gastly",
                            "Haunter",
                            "Drowzee",
                            "Koffing",
                            "Mewtwo",
                            "Mewtwo",
                            "Mew",
                            "Sandshrew",
                            "Diglett",
                            "Dugtrio",
                            "Machop",
                            "Machoke",
                            "Machamp",
                            "Machamp",
                            "Onix",
                            "Hitmonchan",
                            "Clefairy",
                            "Pidgeot",
                            "Mega Pidgeot",
                            "Rattata",
                            "Raticate",
                            "Farfetch'd",
                            "Doduo",
                            "Chansey",
                            "Porygon",
                            "Dragonite",
                            "Blastoise Spirit Link",
                            "Brock's Grit",
                            "Charizard Spirit Link",
                            "Devolution Spray",
                            "Energy Retrieval",
                            "Full Heal",
                            "Maintenance",
                            "Misty's Determination",
                            "Pidgeot Spirit Link",
                            "Pokedex",
                            "Potion",
                            "Professor Oak's Hint",
                            "Revive",
                            "Slowbro Spirit Link",
                            "Super Potion",
                            "Switch",
                            "Venusaur Spirit Link",
                            "Double Colorless Energy",
                            "Grass Energy",
                            "Fire Energy",
                            "Water Energy",
                            "Electric Energy",
                            "Psychic Energy",
                            "Fighting Energy",
                            "Dark Energy",
                            "Metal Energy",
                            "Fairy Energy",
                            "Mega Venusaur",
                            "Mega Charizard",
                            "Mega Blastoise",
                            "Mewtwo",
                            "Pidgeot",
                            "Mega Pidgeot",
                            "Dragonite",
                            "Brock's Grit",
                            "Misty's Determination",
                            "Exeggutor",
                            "Flying Pikachu",
                            "Surfing Pikachu",
                            "Imakuni?'s Doduo",
                            "Here Comes Team Rocket!")

        self.rarity = (  # Regular Pokemon
            "EX Rare",  # 001 Venusar EX
            "EX Rare",
            "Common",
            "Uncommon",
            "Common",
            "Uncommon",
            "Rare",
            "Common",
            "Common",
            "Uncommon",
            "Holo Rare",  # 011 Charizard
            "EX Rare",
            "EX Rare",
            "Common",
            "Holo Rare",
            "Break Rare",
            "Common",
            "Rare",
            "Common",
            "Uncommon",
            "EX Rare",  # 021 Blastoise EX
            "EX Rare",
            "Common",
            "Uncommon",
            "Holo Rare",
            "EX Rare",
            "EX Rare",
            "Common",
            "Rare",
            "Common",
            "Rare",  # 031 Starmie
            "Break Rare",
            "Common",
            "Holo Rare",
            "Common",
            "Holo Rare",
            "Common",
            "Rare Holo",
            "Common",
            "Rare",
            "Common",  # 041 Electabuzz
            "Holo Rare",
            "Common",
            "Uncommon",
            "Holo Rare",
            "Break Rare",
            "Common",
            "Uncommon",
            "Common",
            "Uncommon",
            "Rare",  # 051 Mewtwo
            "EX Rare",
            "Holo Rare",
            "Common",
            "Common",
            "Rare",
            "Common",
            "Uncommon",
            "Holo Rare",
            "Break Rare",
            "Common",  # 061 Onix
            "Holo Rare",
            "Holo Rare",
            "EX Rare",
            "EX Rare",
            "Common",
            "Rare",
            "Rare",
            "Common",
            "Holo Rare",
            "Uncommon",  # 071 Porygon
            "EX Rare",
            # Trainer cards
            "Uncommon",
            "Uncommon",
            "Uncommon",
            "Uncommon",
            "Uncommon",
            "Uncommon",
            "Uncommon",
            "Uncommon",
            "Uncommon",  # 081 Pidgeot Spirit Link
            "Uncommon",
            "Uncommon",
            "Uncommon",
            "Uncommon",
            "Uncommon",
            "Uncommon",
            "Uncommon",
            "Uncommon",
            # Energies
            "Common",
            "Common",  # 091 Grass Engery
            "Common",
            "Common",
            "Common",
            "Common",
            "Common",
            "Common",
            "Common",
            "Common",
            # Full arts
            "Ultra Rare",
            "Ultra Rare",  # 101 M Charizard EX
            "Ultra Rare",
            "Ultra Rare",
            "Ultra Rare",
            "Ultra Rare",
            "Ultra Rare",
            "Ultra Rare",
            "Ultra Rare",
            # Secret rares
            "Secret Rare",
            "Secret Rare",
            "Secret Rare",  # 111 Surfing Pikachu
            "Secret Rare",
            "Secret Rare")

        self.cardtype = ("Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Trainer Item",
                         "Trainer Supporter",
                         "Trainer Item",
                         "Trainer Item",
                         "Trainer Item",
                         "Trainer Item",
                         "Trainer Item",
                         "Trainer Supporter",
                         "Trainer Item",
                         "Trainer Item",
                         "Trainer Item",
                         "Trainer Supporter",
                         "Trainer Item",
                         "Trainer Item",
                         "Trainer Item",
                         "Trainer Item",
                         "Trainer Item",
                         "Energy",
                         "Energy",
                         "Energy",
                         "Energy",
                         "Energy",
                         "Energy",
                         "Energy",
                         "Energy",
                         "Energy",
                         "Energy",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Trainer Supporter",
                         "Trainer Supporter",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Trainer Supporter")
