import cv2
import numpy as np
import math
from PIL import Image
import imagehash
import mysql.connector

username = "#######"  # Your mysql username
password = "#######"  # Your mysql password
databasename = "pokemoncards"  # name of database we want to create


# Creates a CardSet object. Currently has the values for the Evolutions set
class CardSet:
    def __init__(self):
        self.cardnamelist = ("Venusaur EX",
                             "M Venusaur EX",
                             "Caterpie",
                             "Metapod",
                             "Weedle",
                             "Kakuna",
                             "Beedrill",
                             "Tangela",
                             "Charmander",
                             "Charmeleon",
                             "Charizard",
                             "Charizard EX",
                             "M Charizard EX",
                             "Vulpix",
                             "Ninetales",
                             "Ninetales BREAK",
                             "Growlithe",
                             "Arcanine",
                             "Ponyta",
                             "Magmar",
                             "Blastoise EX",
                             "M Blastoise EX",
                             "Poliwag",
                             "Poliwhirl",
                             "Poliwrath",
                             "Slowbro EX",
                             "M Slowbro EX",
                             "Seel",
                             "Dewgong",
                             "Staryu",
                             "Starmie",
                             "Starmie BREAK",
                             "Magikarp",
                             "Gyarados",
                             "Pikachu",
                             "Raichu",
                             "Magnemite",
                             "Magneton",
                             "Voltorb",
                             "Electrode",
                             "Electabuzz",
                             "Zapdos",
                             "Nidoran ♂",
                             "Nidorino",
                             "Nidoking",
                             "Nidoking BREAK",
                             "Gastly",
                             "Haunter",
                             "Drowzee",
                             "Koffing",
                             "Mewtwo",
                             "Mewtwo EX",
                             "Mew",
                             "Sandshrew",
                             "Diglett",
                             "Dugtrio",
                             "Machop",
                             "Machoke",
                             "Machamp",
                             "Machamp BREAK",
                             "Onix",
                             "Hitmonchan",
                             "Clefairy",
                             "Pidgeot EX",
                             "M Pidgeot EX",
                             "Rattata",
                             "Raticate",
                             "Farfetch'd",
                             "Doduo",
                             "Chansey",
                             "Porygon",
                             "Dragonite EX",
                             "Blastoise Spirit Link",
                             "Brock's Grit",
                             "Charizard Spirit Link",
                             "Devolution Spray",
                             "Energy Retrieval",
                             "Full Heal",
                             "Maintenance",
                             "Misty's Determination",
                             "Pidgeot Spirit Link",
                             "Pokedex",
                             "Potion",
                             "Professor Oak's Hint",
                             "Revive",
                             "Slowbro Spirit Link",
                             "Super Potion",
                             "Switch",
                             "Venusaur Spirit Link",
                             "Double Colorless Energy",
                             "Grass Energy",
                             "Fire Energy",
                             "Water Energy",
                             "Electric Energy",
                             "Psychic Energy",
                             "Fighting Energy",
                             "Dark Energy",
                             "Metal Energy",
                             "Fairy Energy",
                             "M Venusaur EX",
                             "M Charizard EX",
                             "M Blastoise EX",
                             "Mewtwo EX",
                             "Pidgeot EX",
                             "M Pidgeot EX",
                             "Dragonite EX",
                             "Brock's Grit",
                             "Misty's Determination",
                             "Exeggutor",
                             "Flying Pikachu",
                             "Surfing Pikachu",
                             "Imakuni?'s Doduo",
                             "Here Comes Team Rocket!")

        self.pokemonlist = ("Venusaur",
                            "Mega Venusaur",
                            "Caterpie",
                            "Metapod",
                            "Weedle",
                            "Kakuna",
                            "Beedrill",
                            "Tangela",
                            "Charmander",
                            "Charmeleon",
                            "Charizard",
                            "Charizard",
                            "Mega Charizard",
                            "Vulpix",
                            "Ninetales",
                            "Ninetales",
                            "Growlithe",
                            "Arcanine",
                            "Ponyta",
                            "Magmar",
                            "Blastoise",
                            "Mega Blastoise",
                            "Poliwag",
                            "Poliwhirl",
                            "Poliwrath",
                            "Slowbro",
                            "Mega Slowbro",
                            "Seel",
                            "Dewgong",
                            "Staryu",
                            "Starmie",
                            "Starmie",
                            "Magikarp",
                            "Gyarados",
                            "Pikachu",
                            "Raichu",
                            "Magnemite",
                            "Magneton",
                            "Voltorb",
                            "Electrode",
                            "Electabuzz",
                            "Zapdos",
                            "Nidoran ♂",
                            "Nidorino",
                            "Nidoking",
                            "Nidoking",
                            "Gastly",
                            "Haunter",
                            "Drowzee",
                            "Koffing",
                            "Mewtwo",
                            "Mewtwo",
                            "Mew",
                            "Sandshrew",
                            "Diglett",
                            "Dugtrio",
                            "Machop",
                            "Machoke",
                            "Machamp",
                            "Machamp",
                            "Onix",
                            "Hitmonchan",
                            "Clefairy",
                            "Pidgeot",
                            "Mega Pidgeot",
                            "Rattata",
                            "Raticate",
                            "Farfetch'd",
                            "Doduo",
                            "Chansey",
                            "Porygon",
                            "Dragonite",
                            "Blastoise Spirit Link",
                            "Brock's Grit",
                            "Charizard Spirit Link",
                            "Devolution Spray",
                            "Energy Retrieval",
                            "Full Heal",
                            "Maintenance",
                            "Misty's Determination",
                            "Pidgeot Spirit Link",
                            "Pokedex",
                            "Potion",
                            "Professor Oak's Hint",
                            "Revive",
                            "Slowbro Spirit Link",
                            "Super Potion",
                            "Switch",
                            "Venusaur Spirit Link",
                            "Double Colorless Energy",
                            "Grass Energy",
                            "Fire Energy",
                            "Water Energy",
                            "Electric Energy",
                            "Psychic Energy",
                            "Fighting Energy",
                            "Dark Energy",
                            "Metal Energy",
                            "Fairy Energy",
                            "Mega Venusaur",
                            "Mega Charizard",
                            "Mega Blastoise",
                            "Mewtwo",
                            "Pidgeot",
                            "Mega Pidgeot",
                            "Dragonite",
                            "Brock's Grit",
                            "Misty's Determination",
                            "Exeggutor",
                            "Flying Pikachu",
                            "Surfing Pikachu",
                            "Imakuni?'s Doduo",
                            "Here Comes Team Rocket!")

        self.rarity = (  # Regular Pokemon
            "EX Rare",  # 001 Venusar EX
            "EX Rare",
            "Common",
            "Uncommon",
            "Common",
            "Uncommon",
            "Rare",
            "Common",
            "Common",
            "Uncommon",
            "Holo Rare",  # 011 Charizard
            "EX Rare",
            "EX Rare",
            "Common",
            "Holo Rare",
            "Break Rare",
            "Common",
            "Rare",
            "Common",
            "Uncommon",
            "EX Rare",  # 021 Blastoise EX
            "EX Rare",
            "Common",
            "Uncommon",
            "Holo Rare",
            "EX Rare",
            "EX Rare",
            "Common",
            "Rare",
            "Common",
            "Rare",  # 031 Starmie
            "Break Rare",
            "Common",
            "Holo Rare",
            "Common",
            "Holo Rare",
            "Common",
            "Rare Holo",
            "Common",
            "Rare",
            "Common",  # 041 Electabuzz
            "Holo Rare",
            "Common",
            "Uncommon",
            "Holo Rare",
            "Break Rare",
            "Common",
            "Uncommon",
            "Common",
            "Uncommon",
            "Rare",  # 051 Mewtwo
            "EX Rare",
            "Holo Rare",
            "Common",
            "Common",
            "Rare",
            "Common",
            "Uncommon",
            "Holo Rare",
            "Break Rare",
            "Common",  # 061 Onix
            "Holo Rare",
            "Holo Rare",
            "EX Rare",
            "EX Rare",
            "Common",
            "Rare",
            "Rare",
            "Common",
            "Holo Rare",
            "Uncommon",  # 071 Porygon
            "EX Rare",
            # Trainer cards
            "Uncommon",
            "Uncommon",
            "Uncommon",
            "Uncommon",
            "Uncommon",
            "Uncommon",
            "Uncommon",
            "Uncommon",
            "Uncommon",  # 081 Pidgeot Spirit Link
            "Uncommon",
            "Uncommon",
            "Uncommon",
            "Uncommon",
            "Uncommon",
            "Uncommon",
            "Uncommon",
            "Uncommon",
            # Energies
            "Common",
            "Common",  # 091 Grass Engery
            "Common",
            "Common",
            "Common",
            "Common",
            "Common",
            "Common",
            "Common",
            "Common",
            # Full arts
            "Ultra Rare",
            "Ultra Rare",  # 101 M Charizard EX
            "Ultra Rare",
            "Ultra Rare",
            "Ultra Rare",
            "Ultra Rare",
            "Ultra Rare",
            "Ultra Rare",
            "Ultra Rare",
            # Secret rares
            "Secret Rare",
            "Secret Rare",
            "Secret Rare",  # 111 Surfing Pikachu
            "Secret Rare",
            "Secret Rare")

        self.cardtype = ("Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Trainer Item",
                         "Trainer Supporter",
                         "Trainer Item",
                         "Trainer Item",
                         "Trainer Item",
                         "Trainer Item",
                         "Trainer Item",
                         "Trainer Supporter",
                         "Trainer Item",
                         "Trainer Item",
                         "Trainer Item",
                         "Trainer Supporter",
                         "Trainer Item",
                         "Trainer Item",
                         "Trainer Item",
                         "Trainer Item",
                         "Trainer Item",
                         "Energy",
                         "Energy",
                         "Energy",
                         "Energy",
                         "Energy",
                         "Energy",
                         "Energy",
                         "Energy",
                         "Energy",
                         "Energy",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Trainer Supporter",
                         "Trainer Supporter",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Pokemon",
                         "Trainer Supporter")


def createDatabase():
    db = mysql.connector.connect(
        host="localhost",
        user=username,
        passwd=password
    )

    mycursor = db.cursor()

    mycursor.execute("SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'pokemoncards'")
    if mycursor.fetchone() is None:
        mycursor.execute("CREATE DATABASE pokemoncards")

    initializeDatabase()


def initializeDatabase():
    db = mysql.connector.connect(
        host="local",
        user=username,
        passwd=password,
        database="pokemoncards"
    )

    mycursor = db.cursor()

    evolutionsSet = CardSet()

    mycursor.execute("CREATE TABLE EvolutionsSet (cardnumber smallint PRIMARY KEY AUTO_INCREMENT, \
        cardname VARCHAR(50), pokemon VARCHAR(11), rarity VARCHAR(13), cardtype VARCHAR(17))")

    mycursor.execute("CREATE TABLE EvolutionsCards (cardnumber smallint PRIMARY KEY, FOREIGN KEY(cardnumber) REFERENCES EvolutionsSet(cardnumber), \
        hash VARCHAR(20), hashmir VARCHAR(20), hashud VARCHAR(20), hashudmir VARCHAR(20))")

    mycursor.execute("CREATE TABLE EvolutionsPokemon (id smallint PRIMARY KEY AUTO_INCREMENT, pokemon VARCHAR, \
        FOREIGN KEY(pokemon) REFERENCES EvolutionsSet(pokemon), \
        type VARCHAR(10), height smallint UNSIGNED, weight smallint UNSIGNED, stage VARCHAR(5))")

    mycursor.executemany("INSERT INTO EvolutionsSet (cardname, pokemon, rarity) VALUES(%s, %s, %s, %s)", \
                         evolutionsSet.cardnamelist, evolutionsSet.pokemonlist, evolutionsSet.rarity,
                         evolutionsSet.cardtype)

    db.commit()


def getCardHashes():
    print("TODO")
