# A Pokedex object contains information about every Pokemon in Kanto (the first 151 Pokemon)
# The mega evolutions of the Pokemon in the Evoltuions Set are also included
class Pokedex:
    def __init__(self):
        # List of all 151 Pokemon + NA slot
        self.pokemon = ("Bulbasaur",  # 001 Bulbasaur
                        "Ivysaur",
                        "Venusaur",
                        "Charmander",
                        "Charmeleon",
                        "Charizard",
                        "Squirtle",
                        "Wartortle",
                        "Blastoise",
                        "Caterpie",
                        "Metapod",  # 011 Metapod
                        "Butterfree",
                        "Weedle",
                        "Kakuna",
                        "Beedrill",
                        "Pidgey",
                        "Pidgeotto",
                        "Pidgeot",
                        "Rattata",
                        "Raticate",
                        "Spearow",  # 021 Spearow
                        "Fearow",
                        "Ekans",
                        "Arbok",
                        "Pikachu",
                        "Raichu",
                        "Sandshrew",
                        "Sandslash",
                        "Nidoran ♀",
                        "Nidorina",
                        "Nidoqueen",  # 031 Nidoqueen
                        "Nidoran ♂",
                        "Nidorino",
                        "Nidoking",
                        "Clefairy",
                        "Clefable",
                        "Vulpix",
                        "Ninetales",
                        "Jigglypuff",
                        "Wigglytuff",
                        "Zubat",  # 041 Zubat
                        "Golbat",
                        "Oddish",
                        "Gloom",
                        "Vileplume",
                        "Paras",
                        "Parasect",
                        "Venonat",
                        "Venomoth",
                        "Diglett",
                        "Dugtrio",  # 051 Dugtrio
                        "Meowth",
                        "Persian",
                        "Psyduck",
                        "Golduck",
                        "Mankey",
                        "Primeape",
                        "Growlithe",
                        "Arcanine",
                        "Poliwag",
                        "Poliwhirl",  # 061 Poliwhirl
                        "Poliwrath",
                        "Abra",
                        "Kadabra",
                        "Alakazam",
                        "Machop",
                        "Machoke",
                        "Machamp",
                        "Bellsprout",
                        "Weepinbell",
                        "Victreebel",  # 071 Victreebel
                        "Tentacool",
                        "Tentacruel",
                        "Geodude",
                        "Graveler",
                        "Golem",
                        "Ponyta",
                        "Rapidash",
                        "Slowpoke",
                        "Slowbro",
                        "Magnemite",  # 081 Magnemite
                        "Magneton",
                        "Farfetch’d",
                        "Doduo",
                        "Dodrio",
                        "Seel",
                        "Dewgong",
                        "Grimer",
                        "Muk",
                        "Shellder",
                        "Cloyster",  # 091 Cloyster
                        "Gastly",
                        "Haunter",
                        "Gengar",
                        "Onix",
                        "Drowzee",
                        "Hypno",
                        "Krabby",
                        "Kingler",
                        "Voltorb",
                        "Electrode",  # 101 Electrode
                        "Exeggcute",
                        "Exeggutor",
                        "Cubone",
                        "Marowak",
                        "Hitmonlee",
                        "Hitmonchan",
                        "Lickitung",
                        "Koffing",
                        "Weezing",
                        "Rhyhorn",  # 111 Rhyhorn
                        "Rhydon",
                        "Chansey",
                        "Tangela",
                        "Kangaskhan",
                        "Horsea",
                        "Seadra",
                        "Goldeen",
                        "Seaking",
                        "Staryu",
                        "Starmie",  # 121 Starmie
                        "Mr. Mime",
                        "Scyther",
                        "Jynx",
                        "Electabuzz",
                        "Magmar",
                        "Pinsir",
                        "Tauros",
                        "Magikarp",
                        "Gyarados",
                        "Lapras",  # 131 Lapras
                        "Ditto",
                        "Eevee",
                        "Vaporeon",
                        "Jolteon",
                        "Flareon",
                        "Porygon",
                        "Omanyte",
                        "Omastar",
                        "Kabuto",
                        "Kabutops",  # 141 Kabutops
                        "Aerodactyl",
                        "Snorlax",
                        "Articuno",
                        "Zapdos",
                        "Moltres",
                        "Dratini",
                        "Dragonair",
                        "Dragonite",
                        "Mewtwo",
                        "Mew",  # 151 Mew
                        "Mega Venusaur",  # -003 Mega Venusaur
                        "Mega Charizard",  # -006 Mega Charizard
                        "Mega Blastoise",  # -009 Mega Blastoise
                        "Mega Pidgeot",  # -018 Mega Pidgeot
                        "Mega Slowbro",  # -080 Mega Slowbro
                        "NA")  # 000 Represents NA

        # Stores the Pokedex number of all Kanto Pokemon
        # If a Pokemon has a mega evolution in the Evolutions set, there is a second entry dedicated to the mega
        # evolution that is the negative of it's pre-mega form (EX: Venusaur = 3; Mega Venusaur = -3)
        self.dexnumber = (1,  # 001 Bulbasaur
                          2,
                          3,
                          4,
                          5,
                          6,
                          7,
                          8,
                          9,
                          10,
                          11,  # 011 Metapod
                          12,
                          13,
                          14,
                          15,
                          16,
                          17,
                          18,
                          19,
                          20,
                          21,  # 021 Spearow
                          22,
                          23,
                          24,
                          25,
                          26,
                          27,
                          28,
                          29,
                          30,
                          31,  # 031 Nidoqueen
                          32,
                          33,
                          34,
                          35,
                          36,
                          37,
                          38,
                          39,
                          40,
                          41,  # 041 Zubat
                          42,
                          43,
                          44,
                          45,
                          46,
                          47,
                          48,
                          49,
                          50,
                          51,  # 051 Dugtrio
                          52,
                          53,
                          54,
                          55,
                          56,
                          57,
                          58,
                          59,
                          60,
                          61,  # 061 Poliwhirl
                          62,
                          63,
                          64,
                          65,
                          66,
                          67,
                          68,
                          69,
                          70,
                          71,  # 071 Victreebel
                          72,
                          73,
                          74,
                          75,
                          76,
                          77,
                          78,
                          79,
                          80,
                          81,  # 081 Magnemite
                          82,
                          83,
                          84,
                          85,
                          86,
                          87,
                          88,
                          89,
                          90,
                          91,  # 091 Cloyster
                          92,
                          93,
                          94,
                          95,
                          96,
                          97,
                          98,
                          99,
                          100,
                          101,  # 101 Electrode
                          102,
                          103,
                          104,
                          105,
                          106,
                          107,
                          108,
                          109,
                          110,
                          111,  # 111 Rhyhorn
                          112,
                          113,
                          114,
                          115,
                          116,
                          117,
                          118,
                          119,
                          120,
                          121,  # 121 Starmie
                          122,
                          123,
                          124,
                          125,
                          126,
                          127,
                          128,
                          129,
                          130,
                          131,  # 131 Lapras
                          132,
                          133,
                          134,
                          135,
                          136,
                          137,
                          138,
                          139,
                          140,
                          141,  # 141 Kabutops
                          142,
                          143,
                          144,
                          145,
                          146,
                          147,
                          148,
                          149,
                          150,
                          151,  # 151 Mew
                          -3,  # -003 Mega Venusaur
                          -6,  # -006 Mega Charizard
                          -9,  # -009 Mega Blastoise
                          -18,  # -018 Mega Pidgeot
                          -80,  # -080 Mega Slowbro
                          0)  # 000 Represents NA

        # Stage of Pokemon: Unevolved = basic; stage 1 = evolved once, stage 2 = evolved twice, Mega = mega evolution
        # Note: EX Cards are basic even if the Pokemon is an evolved Pokemon, this will be accounted for later
        self.stage = ("basic",  # 001 Bulbasaur
                        "1",
                        "2",
                        "basic",
                        "1",
                        "2",
                        "basic",
                        "1",
                        "2",
                        "basic",
                        "1",  # 011 Metapod
                        "2",
                        "basic",
                        "1",
                        "2",
                        "basic",
                        "1",
                        "2",
                        "basic",
                        "1",
                        "basic",  # 021 Spearow
                        "1",
                        "basic",
                        "1",
                        "basic",
                        "1",
                        "basic",
                        "1",
                        "basic",
                        "1",
                        "2",  # 031 Nidoqueen
                        "basic",
                        "1",
                        "2",
                        "basic",
                        "1",
                        "basic",
                        "1",
                        "basic",
                        "1",
                        "basic",  # 041 Zubat
                        "1",
                        "basic",
                        "1",
                        "2",
                        "basic",
                        "1",
                        "basic",
                        "1",
                        "basic",
                        "1",  # 051 Dugtrio
                        "basic",
                        "1",
                        "basic",
                        "1",
                        "basic",
                        "1",
                        "basic",
                        "1",
                        "basic",
                        "1",  # 061 Poliwhirl
                        "2",
                        "basic",
                        "1",
                        "2",
                        "basic",
                        "1",
                        "2",
                        "basic",
                        "1",
                        "2",  # 071 Victreebel
                        "basic",
                        "1",
                        "basic",
                        "1",
                        "2",
                        "basic",
                        "1",
                        "basic",
                        "1",
                        "basic",  # 081 Magnemite
                        "1",
                        "basic",
                        "basic",
                        "1",
                        "basic",
                        "1",
                        "basic",
                        "1",
                        "basic",
                        "1",  # 091 Cloyster
                        "basic",
                        "1",
                        "2",
                        "basic",
                        "basic",
                        "1",
                        "basic",
                        "1",
                        "basic",
                        "1",  # 101 Electrode
                        "basic",
                        "1",
                        "basic",
                        "1",
                        "basic",
                        "basic",
                        "basic",
                        "basic",
                        "1",
                        "basic",  # 111 Rhyhorn
                        "1",
                        "basic",
                        "basic",
                        "basic",
                        "basic",
                        "1",
                        "basic",
                        "1",
                        "basic",
                        "1",  # 121 Starmie
                        "basic",
                        "basic",
                        "basic",
                        "basic",
                        "basic",
                        "basic",
                        "basic",
                        "basic",
                        "1",
                        "basic",  # 131 Lapras
                        "basic",
                        "basic",
                        "1",
                        "1",
                        "1",
                        "basic",
                        "basic",
                        "1",
                        "basic",
                        "1",  # 141 Kabutops
                        "basic",
                        "basic",
                        "basic",
                        "basic",
                        "basic",
                        "basic",
                        "1",
                        "2",
                        "basic",
                        "basic",  # 151 Mew
                        "Mega",  # -003 Mega Venusaur
                        "Mega",  # -006 Mega Charizard
                        "Mega",  # -009 Mega Blastoise
                        "Mega",  # -018 Mega Pidgeot
                        "Mega",  # -080 Mega Slowbro
                        "NA")  # 000 Represents NA

        # Type of first 151 Pokemon according to the card game
        self.type = ("Grass",  # 001 Bulbasaur
                     "Grass",
                     "Grass",
                     "Fire",
                     "Fire",
                     "Fire",
                     "Water",
                     "Water",
                     "Water",
                     "Grass",
                     "Grass",  # 011 Metapod
                     "Grass",
                     "Grass",
                     "Grass",
                     "Grass",
                     "Colorless",
                     "Colorless",
                     "Colorless",
                     "Colorless",
                     "Colorless",
                     "Colorless",  # 021 Spearow
                     "Colorless",
                     "Psychic",
                     "Psychic",
                     "Lightning",
                     "Lightning",
                     "Fighting",
                     "Fighting",
                     "Psychic",
                     "Psychic",
                     "Psychic",  # 031 Nidoqueen
                     "Psychic",
                     "Psychic",
                     "Psychic",
                     "Fairy",  # 035 Clefairy - Fairy type in Evolutions set, may be colorless in older sets
                     "Fairy",  # 036 Clefable - "
                     "Fire",
                     "Fire",
                     "Colorless",
                     "Colorless",
                     "Psychic",  # 041 Zubat
                     "Psychic",
                     "Grass",
                     "Grass",
                     "Grass",
                     "Grass",
                     "Grass",
                     "Grass",
                     "Grass",
                     "Fighting",
                     "Fighting",  # 051 Dugtrio
                     "Colorless",
                     "Colorless",
                     "Water",
                     "Water",
                     "Fighting",
                     "Fighting",
                     "Fire",
                     "Fire",
                     "Water",
                     "Water",  # 061 Poliwhirl
                     "Water",
                     "Psychic",
                     "Psychic",
                     "Psychic",
                     "Fighting",
                     "Fighting",
                     "Fighting",
                     "Grass",
                     "Grass",
                     "Grass",  # 071 Victreebel
                     "Water",
                     "Water",
                     "Fighting",
                     "Fighting",
                     "Fighting",
                     "Fire",
                     "Fire",
                     "Water",
                     "Water",
                     "Lightning",  # 081 Magnemite
                     "Lightning",
                     "Colorless",
                     "Colorless",
                     "Colorless",
                     "Water",
                     "Water",
                     "Psychic",
                     "Psychic",
                     "Water",
                     "Water",  # 091 Cloyster
                     "Psychic",
                     "Psychic",
                     "Psychic",
                     "Fighting",
                     "Psychic",
                     "Psychic",
                     "Water",
                     "Water",
                     "Lightning",
                     "Lightning",  # 101 Electrode
                     "Grass",
                     "Grass",
                     "Fighting",
                     "Fighting",
                     "Fighting",
                     "Fighting",
                     "Colorless",
                     "Psychic",
                     "Psychic",
                     "Fighting",  # 111 Rhyhorn
                     "Fighting",
                     "Colorless",
                     "Grass",
                     "Colorless",
                     "Water",
                     "Water",
                     "Water",
                     "Water",
                     "Water",
                     "Water",  # 121 Starmie
                     "Psychic",
                     "Grass",
                     "Psychic",
                     "Lightning",
                     "Fire",
                     "Grass",
                     "Colorless",
                     "Water",
                     "Water",
                     "Water",  # 131 Lapras
                     "Colorless",
                     "Colorless",
                     "Water",
                     "Lightning",
                     "Fire",
                     "Colorless",
                     "Water",
                     "Water",
                     "Fighting",
                     "Fighting",  # 141 Kabutops
                     "Fighting",
                     "Colorless",
                     "Water",
                     "Lightning",
                     "Fire",
                     "Colorless",  # 147 Dratini - Colorless in Generation 1 & Evolutions (newer cards might be dragon)
                     "Colorless",  # 148 Dragonair - "
                     "Colorless",  # 149 Dragonite - "
                     "Psychic",
                     "Psychic",  # 151 Mew
                     "Grass",  # -003 Mega Venusaur
                     "Fire",  # -006 Mega Charizard
                     "Water",  # -009 Mega Blastoise
                     "Colorless",  # -018 Mega Pidgeot
                     "Water",  # -080 Mega Slowpoke
                     "NA")  # 000 Represents NA

        # Height of Pokemon in meters + 0 for NA
        self.height = (0.7,  # 001 Bulbasaur
                       1.0,
                       2.0,
                       0.6,
                       1.1,
                       1.7,
                       0.5,
                       1.0,
                       1.6,
                       0.3,
                       0.7,  # 011 Metapod
                       1.1,
                       0.3,
                       0.6,
                       1.0,
                       0.3,
                       1.1,
                       1.5,
                       0.3,
                       0.7,
                       0.3,  # 021 Spearow
                       1.2,
                       2.0,
                       3.5,
                       0.4,
                       0.8,
                       0.6,
                       1.0,
                       0.4,
                       0.8,
                       1.3,  # 031 Nidoqueen
                       0.5,
                       0.9,
                       1.4,
                       0.6,
                       1.3,
                       0.6,
                       1.1,
                       0.5,
                       1.0,
                       0.8,  # 041 Zubat
                       1.6,
                       0.5,
                       0.8,
                       1.2,
                       0.3,
                       1.0,
                       1.0,
                       1.5,
                       0.2,
                       0.7,  # 051 Dugtrio
                       0.4,
                       1.0,
                       0.8,
                       1.7,
                       0.5,
                       1.0,
                       0.7,
                       1.9,
                       0.6,
                       1.0,  # 061 Poliwhirl
                       1.3,
                       0.9,
                       1.3,
                       1.5,
                       0.8,
                       1.5,
                       1.6,
                       0.7,
                       1.0,
                       1.7,  # 071 Victreebel
                       0.9,
                       1.6,
                       0.4,
                       1.0,
                       1.4,
                       1.0,
                       1.7,
                       1.2,
                       1.6,
                       0.3,  # 081 Magnemite
                       1.0,
                       0.8,
                       1.4,
                       1.8,
                       1.1,
                       1.7,
                       0.9,
                       1.2,
                       0.3,
                       1.5,  # 091 Cloyster
                       1.3,
                       1.6,
                       1.5,
                       8.8,
                       1.0,
                       1.6,
                       0.4,
                       1.3,
                       0.5,
                       1.2,  # 101 Electrode
                       0.4,
                       2.0,
                       0.4,
                       1.0,
                       1.5,
                       1.4,
                       1.2,
                       0.6,
                       1.2,
                       1.0,  # 111 Rhyhorn
                       1.9,
                       1.1,
                       1.0,
                       2.2,
                       0.4,
                       1.2,
                       0.6,
                       1.3,
                       0.8,
                       1.1,  # 121 Starmie
                       1.3,
                       1.5,
                       1.4,
                       1.1,
                       1.3,
                       1.5,
                       1.4,
                       0.9,
                       6.5,
                       2.5,  # 131 Lapras
                       0.3,
                       0.3,
                       1.0,
                       0.8,
                       0.9,
                       0.8,
                       0.4,
                       1.0,
                       0.5,
                       1.3,  # 141 Kabutops
                       1.8,
                       2.1,
                       1.7,
                       1.6,
                       2.0,
                       1.8,
                       4.0,
                       2.2,
                       2.0,
                       0.4,  # 151 Mew
                       2.4,  #-003 Mega Venusaur
                       1.7,  #-006 Mega Charizard
                       1.6,  #-009 Mega Blastoise
                       2.2,  #-018 Mega Pidgeot
                       2.0,  #-080 Mega Slowbro
                       0.0)  # 000 Represents NA

        self.numpoke = len(self.pokemon)  # Number of Pokemon
